# etc/nginx/bx/conf/bitrix-nuxt.conf
# cache condition variable
set $usecache "";
if ($is_global_cache = 1) {
    set $usecache "${usecache}A";
}

# main config without processing cache pages
include bx/conf/bitrix_general.conf;

# php file processing
location ~ \.php$ {
    proxy_pass $proxyserver;
}

# Main location
location /bitrix {
    proxy_pass $proxyserver;
}

location /local {
    proxy_pass $proxyserver;
}

location /api {
    proxy_pass $proxyserver;
}

location ^~ /_nuxt/ {
    proxy_pass http://127.0.0.1:5174;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    access_log off;
    expires 7d;
    add_header Cache-Control public;
}

location ^~ /__nuxt_devtools__ {
    proxy_pass http://127.0.0.1:5174;
}

location ^~ /__vite_ping {
    proxy_pass http://127.0.0.1:5174;
}

location / {
    proxy_pass http://127.0.0.1:5174;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
}


