<?

$beeralex_user_default_option = [
    'BEERALEX_USER_ENABLE_JWT_AUTH' => 'Y',
    'BEERALEX_USER_JWT_SECRET_KEY' => 'J3p6o4VwJkqU3yX7J2JQ0vS8Z0jvJmJjzqJjCj7y7v4jS2WlDgYj6Q==',
    'BEERALEX_USER_JWT_TTL' => '3600',
    'BEERALEX_USER_JWT_REFRESH_TTL' => '2592000',
    'BEERALEX_USER_JWT_ALGORITHM' => 'HS256',
    'BEERALEX_USER_JWT_ISSUER' => 'beeralex.user',
];
